# Generated by Django 5.2.17 on 2026-08-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'characters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'plays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('act', models.BigIntegerField()),
                ('scene', models.BigIntegerField()),
            ],
            options={
                'db_table': 'scenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('act', models.BigIntegerField()),
                ('scene', models.BigIntegerField()),
                ('start_line', models.BigIntegerField()),
                ('end_line', models.BigIntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'speeches',
                'managed': False,
            },
        ),
    ]
